### PR TITLE
Update database files

### PR DESCRIPTION
**Pull request by RobLoach**
Now that the .dat files are updated, we can update the rdb files.

### CODE REVIEW

**Comment by Kivutar** [comment]
Oops, I missed this one sorry... I already updated those RDB

**Comment by RobLoach** [comment]
:+1:

**Comment by RobLoach** [comment]
@Kivutar Wait, this is to update the compiled `.rdb` files since the new `.dat` files are now in place.

**Comment by Kivutar** [comment]
Lol, I commited and forgot to push x)

**Pull request merged**
