### PR TITLE
Add some ps1 dat

### PR DESCRIPTION
**Pull request by orbea**
Am I doing this right?

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1:

**Comment by orbea** [comment]
Is there anything more I could do to make this PR more complete? I'm still trying to familiarize myself with how libretro-database works so that I can contribute better.

**Comment by RobLoach** [comment]
Nope, you did great. It's good! We have been considering switching from using the serials to CRC .cue checking, but that's another discussion. This PR is good.

**Comment by orbea** [comment]
This commit is tested and works, however it has exposed another issue.
The names on the Little princess discs will be cut off, I suspect game name is just too long...

**Comment by orbea** [comment]
The above issue with the name being cut off is now solved, but it won't detect the boxart for some reason.

Even though the png and dat both seem right...
```
Little Princess +1 - Maru Oukoku No Ningyou Hime 2 (Japan) (Disc 1).cue
Little Princess +1 - Maru Oukoko No Ningyou Hime 2 (Japan) (Disc 1).png
```

**Pull request merged**
