### PR TITLE
Rename to "The 3DO Company - 3DO"

### PR DESCRIPTION
**Pull request by RobLoach**
Fixes https://github.com/libretro/libretro-database/issues/258

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
3DO - 3DO ? T.T

Maybe "The 3DO Company - 3DO"  ?

**Comment by RobLoach** [comment]
@markwidd Thoughts on `The 3DO Company - 3DO`?

**Comment by orbea** [comment]
I agree with `The 3DO Company - 3DO` as that matches to wikipedia.
https://en.wikipedia.org/wiki/The_3DO_Company

Also it just looks better.

**Comment by markwkidd** [comment]
Great to have this new 3DO database, and with credit to its proper developer. Thanks @robloach

**Pull request merged**
