### PR TITLE
Update Atari -2600 to be more like No-Intro.

### PR DESCRIPTION
**Pull request by RetroUp**
This is based on Rom Hunter V11 rom pack from AtariMania but updated to follow No-Intro standards.  It isn't perfect yet but it does make 2600 appear much more like the other No-Intro systems.

### CODE REVIEW

**Comment by lasers** [comment]
Sharing my findings.

|A|B|
|---|---|
|+1,700 | −9,573|
|1877 Games | 565 Games|
| [Just Names](http://sprunge.us/PMZN) | [Just Names](http://sprunge.us/TRFC)|

**Comment by RobLoach** [comment]
These are great changes, but as @lasers pointed out, we're losing a few entries. These are coming through https://github.com/robloach/libretro-dats , would be neat if we could automate the naming of them. With some regex, it may be done. Thoughts?

**Comment by lasers** [comment]
My thought. No regex on script. I cleaned up 7111~ cheat codes enough to assume that it can cause problems in long run especially if done automatically. Just strip off file extension and compare straight up against the database. Skip automatically on perfect match. Pause on non-match and wait for user to give it a new name manually.

When renaming manually, it should also rename same thing in multiple directories too because perfect matches would be automatically skipped just the same way.

This would require small scrubbing directories to make sure all three directories are at least identical and start using a "master" full folder to work with other two. Also, we could add little nifty features like having a script reporting missing files in other directories to a file (so we can share with others) and to use a generic nothumbnail.png in that place.

**Comment by RobLoach** [comment]
Closing in favour of https://github.com/libretro/libretro-database/pull/339 .

**Pull request closed without merging**
