### PR TITLE
Super Mario Bros. 3

### PR DESCRIPTION
**Pull request by SanjuroX**
game genie cheats

### CODE REVIEW

**Comment by Alcaro** [comment]
...three cheat0? Are you sure that works?

And trailing spaces on the last one.

**Comment by SanjuroX** [comment]
fixed the spacing

**Comment by RobLoach** [comment]
@alcaro is right. Will need to be cheat0 cheat1 and cheat2.... See the others for an example.

**Comment by SanjuroX** [comment]
@RobLoach fixed the numbers

**Comment by RobLoach** [comment]
Nicely done! I'll add the cheats prefix after the merge :+1:

**Pull request merged**
