### PR TITLE
Update Elemental Gearbolt (USA) (GameShark).cht

### PR DESCRIPTION
**Pull request by dynaram**
I added infinity health 
Cheat 10 & Cheat 11

### CODE REVIEW

**Comment by dynaram** [comment]
Disregard my request

**Comment by RobLoach** [comment]
What? Anything wrong with it?

**Comment by dynaram** [comment]
I miss understood it. I retracted the request. Sorry

**Comment by RobLoach** [comment]
@dynaram What are your thoughts on chanign the order a bit to make them read a bit better?
https://github.com/libretro/libretro-database/blob/ab182041c86d5ae896357bb939ed2cb8f97df836/cht/Sony%20-%20PlayStation/Elemental%20Gearbolt%20(USA)%20(GameShark).cht

**Comment by dynaram** [comment]
It looks much better thank you

**Pull request merged**
