### PR TITLE
Updated for Star Fox 2 (USA) rom for SNES Classic

### PR DESCRIPTION
**Pull request by Zerauskire**
Updated SNES .dat file for release of Star Fox 2 (USA) official rom that comes pre-loaded on the new SNES Classic

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks like it's....

```
	<game name="Star Fox 2 (USA)">
		<description>Star Fox 2 (USA)</description>
		<rom name="Star Fox 2 (USA).sfc" size="1048576" crc="87653732" md5="7D66769F53CB3FB7F5C73044876DB240" sha1="1135A2A6CB786AC7523E81DD553DC81AAA266F51"/>
	</game>
```

**Comment by Zerauskire** [comment]
Oops. My Bad. Ok. I'll change that.

**Comment by Zerauskire** [comment]
I'll be honest. I don't know a whole lot about GitHub. I'm still learning. I think I've corrected it. Sorry.

**Comment by twinaphex** [comment]
@RobLoach - Let me know when this is fit for merge, thanks.

**Comment by RobLoach** [comment]
@Zerauskire Thanks a lot for the work! I've fixed it up and removed the duplicate entries in https://github.com/libretro/libretro-database/pull/530 :+1: 

Star Fox 2 time! :fox_face:

**Comment by Zerauskire** [comment]
@RobLoach Thanks! I'll stick to updating .cht files from now on. That's more in my wheelhouse. :-)

**Comment by RobLoach** [comment]
Haha, no worries! It is a bit more complicated than it needs to be. Would like to revamp the system sometime to make it easier to manage.

**Pull request closed without merging**
