### PR TITLE
hack updates

### PR DESCRIPTION
**Pull request by i30817**
As was expected, the super robot 'no change in hash' in the previous update was a uploader error at romhacking.net.

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks like a conflict since the last merge. Mind resolving? Thanks!

**Comment by i30817** [comment]
Ugh. Tried to 'fix' the merge conflict with amending the same changes on master but it didn't work, then tried to 'interactive conflict solver' on this page and it created another commit... It's probably better to close this and open a new one.

**Comment by RobLoach** [comment]
You should be able to do it in the GitHub UI directly with that Resolve Conflict button.

**Comment by i30817** [comment]
That was  what created the new merge commit. I prefer clean history, so a new branch & PR is already opened.

**Pull request closed without merging**
