### PR TITLE
Update and rename Spectravideo.dat to Spectravideo - SVI-318 - SVI-328.dat

### PR DESCRIPTION
**Pull request by WizzardSK**

### CODE REVIEW

**Comment by RobLoach** [comment]
If we rename this, we will also have to update the playlist name that appears in RetroArch. Intentional?

**Comment by WizzardSK** [comment]
I am not sure. I just wanted to correct the name to have "System - Name" format like other systems. Not sure where the playlist name is defined in RetroArch. If is it not a correct change, close that, please.

**Comment by RobLoach** [comment]
I'm good with either one. Makes sense to me!

**Comment by WizzardSK** [comment]
Ok, fixed that!

**Pull request merged**
