### PR TITLE
(N64) Added SSSV hacks, filled in blanks

### PR DESCRIPTION
**Pull request by Jaffacakelover**
Added rom hacks for Space Station Silicon Valley (bug fix patches).
Filled out the blank entries (lines only had Franchise and CRC listed before).

### CODE REVIEW

**Comment by RobLoach** [comment]
Mind submitting the DAT file updates too?

**Comment by RobLoach** [comment]
Oh, apologies... These are the no-intro ones. Mind adding them to the `hacks` DB? https://github.com/libretro/libretro-database/blob/master/metadat/hacks/Nintendo%20-%20Nintendo%2064.dat

I understand it's a lot of work to move these around, so I really appreciate your patience.

**Comment by Jaffacakelover** [comment]
Will do!
I've noticed that there are a few translation patches in the hacks database... is this where they're supposed to live? There were a bunch of translations in the main Game Boy Advance database when I worked on that, would they need moving out into their own hacks file?

**Comment by RobLoach** [comment]
All of the DAT files get pulled into the RDB files. We just keep the DATs cleaned up.

**Comment by RobLoach** [comment]
Brought these in :wink: ... Thanks a lot.

**Pull request closed without merging**
