### PR TITLE
Added some goodtools metadats and updated rdb

### PR DESCRIPTION
**Pull request by JuanVCS**
Should help people not finding their roms with the scanner and they also have some translations/romhacks.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I'm not 100% but I thought we couldn't include GoodTools sets due to licensing...?

**Comment by JuanVCS** [comment]
I'm adding a few more sets to the already existing https://github.com/libretro/libretro-database/tree/master/metadat/goodtools

**Comment by RobLoach** [comment]
I'm not a license lawyer, but to my knowledge, it's the GoodTools binaries and source files that we cannot host. Looking at the [Hosting License](https://en.wikipedia.org/wiki/GoodTools#Hosting_license), that's what I come to understand. GoodTools is a set of tools, these DAT files are files that JuanVCS built, so they should be good to go.

Is anything missing before we merge this, @JuanVCS?

**Comment by JuanVCS** [comment]
This is all I have at the moment so I guess they're good to go. BTW they were built with clrmamepro's dir2dat utility, no goodtools involved.

**Comment by hizzlekizzle** [comment]
Quoted from #243 :

> You are NOT authorized to reverse engineer or otherwise extract the
> database of names included inside the GoodTools. This includes
> generating databases for other renaming programs.

This sounds like we're not allowed to do much of anything with them. However, this seems like a pretty broad claim and I don't know how enforceable and/or legally legitimate it is.

**Comment by RobLoach** [comment]
Hmmmm, we should likely remove them then. Thoughts?

**Comment by twinaphex** [comment]
Do other programs disregard this stipulation inside the license?

**Comment by zandrorev** [comment]
The GoodTools use various methods to determine whether roms of varying structure match an entry. This includes looking past the sporadic inclusion of arbitrary headers in many sets, accounting for byte order or interleaving of N64, MSG/MGX format for NEC PCE, and so on.  Despite these checks, the GoodTools will not modify the roms to complement its internal DB, for in an emulator there could be dependence on instructions in a rom's header.

A dir2dat would capture a collector's (or his source's) unique form of a set, and wouldn't always represent somebody else's accurately.  We have been battling GoodSet dir2dats for years, not just because of licenses, but also because they create conflict and misunderstanding from those who are not sufficiently aware of the dynamics of the GoodSets.

ClrMamePro was equipped with header checker/skipper functionality which can be used to mimic some of the the GoodTools methods, but not all, and only leads to the same results of giving leniency to differing sets rather than assuring strict conformity (which would break compatibility).

I have to recommend against incorporating dir2dat forms of the GoodTools sets, especially since they are not fully reliable portrayals of them, unlike No-Intro dats, which provides hashes of headerless roms and otherwise aims to adhere to predetermined parameters.

**Pull request merged**
