### PR TITLE
Added Sega Genesis Hacks

### PR DESCRIPTION
**Pull request by Europia79**
- Sorted Alphabetically
- Added:
NHL '94
Psy-O-Blade
Surging Aura

### CODE REVIEW

**Comment by RobLoach** [comment]
Thank you!

**Comment by i30817** [comment]
Does it matter they're sorted? Because i made the previous versions on purpose to clearly divide those hacks that were 'not done by my tool' (rhdndat) from those that were manually added.

The advantage of using rhdndat is that i don't have to care about manual updates and the diffs stay minimal and easy to review. So i'm basically asking this is reverted to place the new entries on top unless it's really important.

**Comment by i30817** [comment]
Also @RobLoach, is there a comment marker that works for ignoring a line in these dat files? I'm thinking of adding a line `#following entries added by rhdndat` to make the division explicit.

**Comment by Europia79** [comment]
So... I wanted to add some entries... So naturally, the question arises, "where do I put them ?"  I mean, there's several different strategies.  I could prepend new entries at the start of the file ?  I could append new entries to the end of the file ?  I could insert new entries in the middle of the file ?  But with the lack of an apparent standard, it's not immediately obvious to new-comers (like me) what the correct answer is.

And a logical argument can be made for all three strategies.  But I disagree that there should be different rules for different people.  There should be one rule and one standard for all people to follow... including automated tools.  This is just the nature of software development:  That tools are made to specification.

So really, we both have the exact same problem:  No standardize rule for writing new entries.

I mean, apparently, it's a problem for your tool ?  Altho, I don't exactly understand why ?  Can you elaborate on why your tool needs a division between it's own automated entries and the entries generated by other tools ?  What exactly happens when there's no division and they're all mixed together ?

**Comment by Europia79** [comment]
Feel free to call me on Discord:  I'm `Europia79#7146`

I'm also in the Discord servers for `romhackingdotnet` and `libretro`

I hate unresolved issues like this, and I feel like it'd much faster to collaborate over a quick discord session, knock it out, then come back & post a solution that everyone will be happy with.

Also, thanks for pointing out those errors.

**Comment by RobLoach** [comment]
> Does it matter they're sorted?

No. Order doesn't matter.

> The advantage of using rhdndat is that i don't have to care about manual updates and the diffs stay minimal and easy to review. So i'm basically asking this is reverted to place the new entries on top and ditch the sorting unless it's really important, and if so i can sort the rhdndat entries myself too.

That's okay, we can review in the diff.

> Also i'd suggest not naming hack roms with (USA) in the name. The standard which my tool has been following is the original rom name for translations followed by [T-Lang by authors] and the hack name for hacks followed by [Hack by authors] and consistency is user friendly.

`(USA)` is the region. It's helpful to have that to match the source rom region. You can have both (USA) and [T-Lang] flags.

> is there a comment marker that works for ignoring a line in these dat files in the tools that process them?

You can have `comment` entries, similar to:
https://github.com/libretro/libretro-database/blob/master/dat/BIOS.dat#L15

> I hate unresolved issues like this, and I feel like it'd much faster to collaborate over a quick discord session, knock it out, then come back & post a solution that everyone will be happy with.

There's no unresolved issue here. We've done our best to place DAT files in logical places. The documentation and formatting could improve, but this is working for now. If you have any suggestions, feel free to create a new issue. :+1:

**Comment by i30817** [comment]
> I mean, apparently, it's a problem for your tool ? 
No, it works fine. Sort of, it's complicated code to match, but at most you'll end up with duplicate entries you'll need to correct. 

The problem such as it is, is that for me it's much easier to check what few romhacks are not automatically checked if they start on the start of the file, and to remove duplicates in romhacking.net gets it and i can use the tool to check for updates.

**Comment by Europia79** [comment]
I"ll fix that mistake now... From looking at the RetroArch database, it appears that it uses the fully-qualified names for the `name` & `description` fields and the abbreviation for the `rom_name` field.

**Pull request merged**
