### PR TITLE
Update Nintendo DS/DSi and Genesis *.rdb, Mega Man 3 (USA) from NES and others

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1:

**Comment by RobLoach** [comment]
Last time I updated these, I split the large pull request into smaller ones for each individual file. Might help get movement on it.

**Comment by sergiobenrocha2** [comment]
Well, at least I commit many times.

**Comment by RobLoach** [comment]
Makes cherry-picking them easy :wink:

**Comment by sergiobenrocha2** [comment]
Nah, next time I do it.

@twinaphex

**Comment by sergiobenrocha2** [comment]
Like I said, it has many commits, if you want to see the diff just click in each commit. Better than a huge diff in only one commit.

**Comment by sergiobenrocha2** [comment]
@twinaphex are there any problem with this PR?

**Pull request merged**
