### PR TITLE
Move summonthethunder's cheats to NES

### PR DESCRIPTION
**Pull request by RobLoach**
@summonthethunder These belong in the NES folder? https://github.com/libretro/libretro-database/issues/981

### CODE REVIEW

**Comment by summonthethunder** [comment]
Hello! #981 – Those cheats go to NES.  PCE/TG16 is already correct so that can stay.#982 – Those cheats go to FDS. Sorry for the confusion!  Did that help? Sent from Mail for Windows 10 From: Rob LoachSent: Tuesday, February 4, 2020 8:01 PMTo: libretro/libretro-databaseCc: summonthethunder; MentionSubject: [libretro/libretro-database] Move summonthethunder's cheats to NES (#985) @summonthethunder These belong in the NES folder? #981You can view, comment on, or merge this pull request online at:  https://github.com/libretro/libretro-database/pull/985Commit SummaryMove summonthethunder's cheats to NESFile ChangesD cht/Nintendo - Family Computer Disk System/Flying Dragon - The Secret Scroll (USA).cht (65) R cht/Nintendo - Nintendo Entertainment System/10-Yard Fight (USA, Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/1942 (Japan, USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/1943 - The Battle of Midway (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/1945.cht (0) R cht/Nintendo - Nintendo Entertainment System/2-in-1 Cosmo Cop + Cyber Monster (Sachen) [U][!].cht (0) R cht/Nintendo - Nintendo Entertainment System/3-D WorldRunner (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/4-in-1 Super Cool Boy.cht (0) R cht/Nintendo - Nintendo Entertainment System/52-in-1 -Multicart.cht (0) R cht/Nintendo - Nintendo Entertainment System/720 Degrees (USA)cht (0) R cht/Nintendo - Nintendo Entertainment System/8 BIT XMAS 2009.cht (0) R cht/Nintendo - Nintendo Entertainment System/8 Eyes (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/ASO - Armored Scrum Object (Japan) (En).cht (0) R cht/Nintendo - Nintendo Entertainment System/Abadox - The Deadly Inner War (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Abarenbou Tengu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Aces - Iron Eagle III (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Action in New York (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Addams Family, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Addams Family, The - Pugsley's Scavenger Hunt (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Addams Family, The - Uncle Fester's Quest (USA) (Beta).cht (0) R cht/Nintendo - Nintendo Entertainment System/Advanced Dungeons & Dragons - DragonStrike (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Advanced Dungeons & Dragons - Dragons of Flame (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Advanced Dungeons & Dragons - Heroes of the Lance (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Advanced Dungeons & Dragons - Hillsfar (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Advanced Dungeons & Dragons - Pool of Radiance (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventure Island (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventure Island 3 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventure Island Classic (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventure Island II (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures in the Magic Kingdom (USA).xml (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Bayou Billy, The (USA).xml (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Dino Riki (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Dr. Franken, The (USA) (Proto).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Gilligan's Island, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Lolo (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Lolo (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Lolo (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Lolo 2 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Lolo 3 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Rad Gravity, The (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Rad Gravity, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Rocky and Bullwinkle and Friends, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Adventures of Tom Sawyer (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/After Burner (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Aigina no Yogen - Balubalouk no Densetsu Yori (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Air Fortress (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Air Fortress (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Airball (USA) (Proto 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Airwolf (Japan) (Kyugo).cht (0) R cht/Nintendo - Nintendo Entertainment System/Airwolf (USA) (Acclaim).cht (0) R cht/Nintendo - Nintendo Entertainment System/Akuma-kun - Makai no Wana (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Akumajou Densetsu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Akumajou Dracula (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Akumajou Special - Boku Dracula-kun (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Al Unser Jr. Turbo Racing (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Aladdin (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alex DeMeo's Race America (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alfred Chicken (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alien 3 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alien Syndrome (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Aliens.cht (0) R cht/Nintendo - Nintendo Entertainment System/All Night Nippon Super Mario Bros. (J) (FDS Conversion) [a1].cht (0) R cht/Nintendo - Nintendo Entertainment System/All Night Nippon Super Mario Bros. (J) (FDS Conversion).cht (0) R cht/Nintendo - Nintendo Entertainment System/All-Pro Basketball (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alpha Mission (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Alter Ego.cht (0) R cht/Nintendo - Nintendo Entertainment System/Amagon (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/American Dream (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/American Gladiators (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Antarctic Adventure (J) [T+Eng1.00_DvD Translations].cht (0) R cht/Nintendo - Nintendo Entertainment System/Anticipation (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arabian Dream Scheherazade (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arch Rivals - A Basketbrawl! (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Archon (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Argos no Senshi - Hachamecha Daishingeki (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Argus (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arkanoid (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arkanoid (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arkanoid II (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Arkista's Ring (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Armadillo (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Armadillo 2.cht (0) R cht/Nintendo - Nintendo Entertainment System/Artelius (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Asmik-kun Land (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Assimilate.cht (0) R cht/Nintendo - Nintendo Entertainment System/Asterix (Europe) (En,Fr,De,Es,It).cht (0) R cht/Nintendo - Nintendo Entertainment System/Astro Fang - Super Machine (Japan)cht (0) R cht/Nintendo - Nintendo Entertainment System/Astro Robo Sasa (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Astyanax (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Athena (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Atlantis no Nazo (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Attack Animal Gakuen (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Attack of the Killer Tomatoes (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Aussie Rules Footy (Australia).cht (0) R cht/Nintendo - Nintendo Entertainment System/B-Wings (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Babel no Tou (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Back to the Future (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Back to the Future Part II & III (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bad Dudes (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bad Dudes vs. Dragon Ninja (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bad News Baseball (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bad Street Brawler (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bakushou!! Jinsei Gekijou 2 (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Ballblazer (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Balloon Fight (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Balloon Fight (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Balloon Fight (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baltron (Japan)cht (0) R cht/Nintendo - Nintendo Entertainment System/Banana (J).cht (0) R cht/Nintendo - Nintendo Entertainment System/Banana Prince (Germany).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bananan Ouji no Daibouken (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bandai Golf - Challenge Pebble Beach (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bandit Kings of Ancient China (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bao Qing Tian (Ch).cht (0) R cht/Nintendo - Nintendo Entertainment System/Barbie (USA) (Rev 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Barbie (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bard's Tale, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Barker Bill's Trick Shooting (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball (USA, Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball Fighter (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball Simulator 1.000 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball Stars (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Baseball Stars II (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded (USA) (Rev 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded (USA) (Rev 2).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded 3 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded 4 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bases Loaded II - Second Season (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bashi Bazook - Morphoid Masher (USA) (Proto) (1989-05-29).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman - Return of the Joker (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman - The Video Game (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman - The Video Game (USA) (Beta) (Earlier).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman - The Video Game (USA) (Beta) (Later).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman - The Video Game (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batman III.xml (0) R cht/Nintendo - Nintendo Entertainment System/Batman Returns (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Batsu & Terry - Makyou no Tetsujin Race (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Baseball (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Chess (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Formula (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Kid- Fortress of Peril (v1.0).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Kid- Fortress of Peril (v1.1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle Stadium - Senbatsu Pro Yakyuu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle of Olympus, The (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battle of Olympus, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/BattleCity (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battleship (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battletoads (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battletoads (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Battletoads-Double Dragon (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Be-Bop-Highschool - Koukousei Gokuraku Densetsu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Beauty and the Beast (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Beetlejuice (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Best of the Best - Championship Karate (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bigfoot (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bikkuriman World - Gekitou Sei Senshi (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bill & Ted's Excellent Video Game Adventure (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bill Elliott's NASCAR Challenge (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Binary Land (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bio Force Ape (Japan) (En) (Proto).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bio Miracle Bokutte Upa (J) [T+Eng1.00_Vice].cht (0) R cht/Nintendo - Nintendo Entertainment System/Bio Miracle Bokutte Upa (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bio Senshi Dan - Increaser Tono Tatakai (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bionic Commando (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bird Week (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Black Bass, The (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Black Bass, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blades of Steel (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blaster Master (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blaster Master (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blodia Land - Puzzle Quest (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bloody Warriors - Shan-Go no Gyakushuu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blue Marlin, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blue Shadow (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Blues Brothers, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bo Jackson Baseball (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bokosuka Wars (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bomber King (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bomber Man (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bomberman (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bomberman Collection.cht (0) R cht/Nintendo - Nintendo Entertainment System/Bomberman II (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bonk's Adventure (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Booby Kids (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Boogerman II.cht (0) R cht/Nintendo - Nintendo Entertainment System/Boulder Dash (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bram Stoker's Dracula (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Break Time - The National Pool Tour (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/BreakThru (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bubble Bobble (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bubble Bobble Part 2 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bucky O'Hare (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bugs Bunny Birthday Blowout, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bugs Bunny Crazy Castle, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bugs Bunny Fun House (USA) (Beta).cht (0) R cht/Nintendo - Nintendo Entertainment System/Bump 'n' Jump (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Burai Fighter (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cabal (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cadillac (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Caesars Palace (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/California Games (USA)cht (0) R cht/Nintendo - Nintendo Entertainment System/California Raisins - The Grape Escape (USA) (Proto 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Capcom's Gold Medal Challenge '92 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain America and the Avengers (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain ED (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Planet and the Planeteers (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Saver (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Silver (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Skyhawk (USA) (Rev 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Skyhawk (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Tsubasa (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Captain Tsubasa II - Super Striker (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Casino Kid (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Casino Kid II (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castelian (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castelian (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castle Excellent (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castle Quest (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castle of Dragon (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlequest (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania (USA) (Rev 1).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania II - Simon's Quest (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania II - Simon's Quest (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania III - Dracula's Curse (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Castlevania III - Dracula's Curse (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cat Ninden Teyandee (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Caveman Games (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chack'n Pop (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Challenge of the Dragon (Sachen) [U][!].cht (0) R cht/Nintendo - Nintendo Entertainment System/Challenger (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Championship Bowling (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Championship Lode Runner (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Championship Pool (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Championship Rally (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chaos World (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chessmaster, The (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chester Field - Ankoku Shin e no Chousen (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chiisana Obake - Acchi Socchi Kocchi (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chiki Chiki Machine Mou Race (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chip 'n Dale - Rescue Rangers (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chip 'n Dale - Rescue Rangers (USA)cht (0) R cht/Nintendo - Nintendo Entertainment System/Chip 'n Dale - Rescue Rangers 2 (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chip to Dale no Daisakusen (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chip to Dale no Daisakusen 2 (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chitei Senkuu Vazolder (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Choplifter (Japan) (En).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chou Fuyuu Yousai Exed Exes (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chou-Wakusei Senki - MetaFight (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Choujikuu Yousai - Macross (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Choujin Sentai Jetman (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Choujinrou Senki - Warwolf (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chris Evert & Ivan Lendl in Top Players' Tennis (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chrono Trigger.cht (0) R cht/Nintendo - Nintendo Entertainment System/Chubby Cherub (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chuck Yeager's Fighter Combat.cht (0) R cht/Nintendo - Nintendo Entertainment System/Chuugoku Janshi Story - Tonfuu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chuugoku Senseijutsu (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Chuuka Taisen (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Circus Caper (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Circus Charlie (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/City Adventure Touch - Mystery of Triangle (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/City Connection (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/City Connection (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Clash at Demonhead (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Classic Concentration (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cliffhanger (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Clu Clu Land (World).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cobra Command (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cobra Triangle (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cocoron (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Code Name - Viper (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Commando (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Conan (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Conflict (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Conquest of the Crystal Palace (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Contra (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Contra (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Contra Force (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cool World (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cosmic Epsilon (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cosmic Wars (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cosmo Police Galivan (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cowboy Kid (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crackout (Europe).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crackout (USA) (Proto).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crash 'n' the Boys - Street Challenge (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crayon Shin-chan - Ora to Poi Poi (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crazy Climber (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crisis Force (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/CrossFire (Japan).cht (0) R cht/Nintendo - Nintendo Entertainment System/CrossFire (USA) (Proto).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crystalis (U) (Prototype).cht (0) R cht/Nintendo - Nintendo Entertainment System/Crystalis (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cyber Stadium Series - Base Wars (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cyberball (USA).cht (0) R cht/Nintendo - Nintendo Entertainment System/Cybernoid - The Fighting Machine (USA).cht (0) Patch Links:https://github.com/libretro/libretro-database/pull/985.patchhttps://github.com/libretro/libretro-database/pull/985.diff—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by summonthethunder** [comment]
Hello! #981 – Those cheats go to NES.  PCE/TG16 is already correct so that can stay.#982 – Those cheats go to FDS. Sorry for the confusion!  Did that help?

**Comment by RobLoach** [comment]
So this pull request is correct then? I moved them all into cht/NES

**Comment by summonthethunder** [comment]
Yes, #981 is for the NES folder, looks correct to me.  #982 is the FDS cheats.

**Pull request merged**
