### PR TITLE
Update Quake.dat

### LINKED ISSUE #1238: Quake.dat: add PAK1.PAK and directory
Insufficient PAK1.PAK for Quake.
Add directory to identify games.

### PR DESCRIPTION
**Pull request by satorope**
Add PAK1.PAK to Quake.
Add directory to identify games.
Closes #1238

I don't have Quake v1.01, so I didn't add pak1.pak to it.

### CODE REVIEW

**Comment by RobLoach** [comment]
I don't think subdirectories work in the database scanner.

**Comment by satorope** [comment]
DAT files help you organize your ROMs. Then, I decided that there was no demerit to add the folder because it doesn't affect the RDB.

**Comment by RobLoach** [comment]
Sounds good with me. Thanks.

**Comment by metchebe** [comment]
Hello. The scanner does not work for me anymore after this update. I'm pretty sure adding the folders broke the database.

Tested with pak0.pak CRC32 74e3b084.

**Pull request merged**
