### PR TITLE
Added GOG games

### PR DESCRIPTION
**Pull request by Jaffacakelover**
Added entries for the GOG releases of 'Space Quest II', 'The Dig', 'Simon the Sorcerer II' and 'Leisure Suit Larry 3'. They now add to ScummVM Retroarch playlist after scan.

### CODE REVIEW

**Comment by Jaffacakelover** [comment]
In [libretro-database-scummvm](https://github.com/RobLoach/libretro-database-scummvm/tree/master), The `DATs` folder only contains one empty '.gitkeep' file, and the main folder has a shortcut to this repo (`libretro-database @ 7993b99`).
It looks like Scummvm.dat [is in an old branch](https://github.com/RobLoach/libretro-database-scummvm/tree/75013e4fb83be9df97f377d7850e138b348f8465) and not in the master?

**Comment by twinaphex** [comment]
hi there, can you fix the merge conflict above?

**Comment by RobLoach** [comment]
I'll add them manually. Could be that there wasn't a unique ROM found from the entries.

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-database-scummvm/commit/0623f60016bb309f89140eeff63dc305de5908e1#diff-a54bda32dfc57cd9a3c59d5494d2ee7aa426d3ca6a0bd2b5147347f2c2d64e17

**Pull request closed without merging**
