### PR TITLE
Added Nintendo DS cheats from the usrcheat database

### PR DESCRIPTION
**Pull request by Rubonnek**
The parser for the usrcheat database in XML can be can be found [here](https://github.com/Rubonnek/usrcheat_to_libretro_cht_parser/).

There are many cheats related to the DS backlight control that are just useless. I could parse them off of these files later if needed, but for now a review would be great.

Related issue: #467.

### CODE REVIEW

**Comment by RobLoach** [comment]
Wow! Nicely done!

**Comment by Rubonnek** [comment]
Thanks! :D

**Comment by GizmoChapa** [comment]
Can anyone make a video guide on this? It's a bit confusing to me as a noob who doesn't do coding with files etc.

**Comment by Rubonnek** [comment]
@GizmoChapa What I did is not trivial. Can't be explained easily in a single video since you'll have to learn a programming language that doesn't get in your way when manipulating files if you want to code this as fast as I did. A language like Perl or Python works, but I used Perl in my case. And then you'll need to learn the regular expressions used in that language, and also learn about a bit about using file handles for creating new files.

Apart from that you still have to find a library for parsing the usrcheat database, and one for parsing XML files works since the binary database can be converted to that format with `r4cee`, and then you need learn how to use that library. Add to that a bit of math for counting the cheats within the database, knowing what ASCII, UTF-8, UTF-16 and many others mean, and also learning and how to construct a recursive loop and you are mostly good to go. The rest is just about analyzing the usrcheat database in XML format to remove any unnecessary text and you just need to come up with your own algorithm to do that. There's no guide, there's nothing that will help you building that algorithm other than your own ingenuity and experience with the programming language you are using by knowing what you can do with it. And that is the main reason why, unfortunately, making a video won't help.

Like I mentioned in the original post, you can check how I did it by reading the code I wrote [here](https://github.com/Rubonnek/usrcheat_to_libretro_cht_parser/). You can ignore the rest of the files there, except these:

* `usrcheat_parser.pl` - which details step by step how to separate the database into the different files I submitted here. Written in Perl 5.
* `usrcheat_database.xml` - which is the raw usrcheat database in XML form that is read by the program above, and
* `mini-test.xml` - which is just an excerpt of that usrcheat database I manually wrote to rapidly test if my Perl script was working as intended.

You are free to clone my repository, install the XML::Parser Perl library on your computer, modify my Perl script (i.e. `usrcheat_parser.pl`), and provide that `mini-test.xml` file to the program by running in Linux:

```shell
./usrcheat_parser.pl -i mini-test.xml
```
OR in Windows, which I believe this should work in `cmd`:

```shell
perl -f usrcheat_parser.pl -i mini-test.xml
```
to see how the changes you made affects the execution of the program.

Unfortunately, this is as far as I can help you, but I'll answer any specific questions you have about my code.

Learning a programming language depends heavily on you and your interest in it, and I'm confident anyone who wants to learn a new programming language, can learn it on their own using all the available resources online.

**Pull request merged**
