### PR TITLE
Update Atari - 2600.dat

### PR DESCRIPTION
**Pull request by RetroUp**
Replaced dashes with tildes in alt title separation.

Renamed Unknown Activision Game #2 to Mazy Match.

Deleted Unknown Datatech Game. Duplicate of Chopper Command.

### CODE REVIEW

**Comment by RobLoach** [comment]
> Replaced dashes with tildes in alt title separation.

Any reason why? The dashes appear in No-Intro more often.

**Comment by RetroUp** [comment]
No-Intro is supposed to convert colons to dashes and alt title separation to tildes. I believe most dats correctly do so.

Example see dashes and tildes in https://github.com/libretro/libretro-database/blob/master/metadat/no-intro/Sega%20-%2032X.dat

**Comment by lasers** [comment]
For tildes in `Sega - 32X` if nobody wanted to look. 
```
After Burner Complete ~ After Burner (Japan, USA)
Chaotix ~ Knuckles' Chaotix (Japan, USA)
Cyber Brawl ~ Cosmic Carnage (Japan, USA)
Parasquad ~ Zaxxon's Motherbase 2000 (Japan, USA)
Shadow Squadron ~ Stellar Assault (USA, Europe)
```


> **2.1.5 Subtitles**
>Subtitles and pretitles are always separated from the main title by a hyphen “ - “. Titles that use a different separation style (ex. colon or “~ Subtitle ~”) will be converted to a hyphen style. If the first word of a subtitle is a common article it will NOT be moved to the end. 
>
>Example 1: Castlevania II - Belmont's Revenge 
Example 2: Double Dragon - The Ultimate Team 
Example 3: Legend of Zelda, The - A Link to the Past

_Source: The Official No-Intro Convention (20071030).pdf_

**Comment by RobLoach** [comment]
No-Intro pushed up their Atari 2600 DAT. Could you push these up to them in the Forums?

**Pull request closed without merging**
