### PR TITLE
Added pokemon prism.

### PR DESCRIPTION
**Pull request by fennectech**
Added pokemon prism bolth standard and debug version

### CODE REVIEW

**Comment by fennectech** [comment]
@RobLoach  Did i do it right this time?

**Comment by RobLoach** [comment]
Looks great! Thanks so much :+1: 

Next rebuild, they'll be in the DB.

**Comment by fennectech** [comment]
it says closed with unmerged commits.  what should i do?

**Comment by RobLoach** [comment]
Weird... Thought I clicked Merge. Thanks for noticing!

**Comment by fennectech** [comment]
Your welcome xD. we’ve all clicked the wrong button.  I once got source and target harddrives mixed up in an imaging operation.     blew out my entire system with a blank image.

**Pull request merged**
