### PR TITLE
snes: Add Super Famicon Wars (Japan)

### PR DESCRIPTION
**Pull request by RobLoach**
@meepingsnesroms was looking to play this netplay. While soft-patching workds, having it in the menu makes life easier.

### CODE REVIEW

**Comment by i30817** [comment]
Ok, _now_ can i add the fairly complete dat list of nes and snes hacks you rejected before?

This was there - among with many other missing not not updated patches.

**Comment by RobLoach** [comment]
> Ok, now can i add the fairly complete dat list of nes and snes hacks you rejected before?

All? No... But the most popular ones, yes.

**Comment by i30817** [comment]
Yeah screw that. I prefer to figure out how to create my own rdb if you're going to keep sabotaging this one to 'parcials'. Though admittedly it's kind of useless atm because retroarch upstream is sabotaging itself with serials.

**Comment by i30817** [comment]
I seriously don't even understand the point of complaining about performance of the _database_ of all things. I'm sure that you're aware that the scanner dominates (crushes) the performance cost of that usecase compared to the lookup and that cost is directly proportional to the size of the rom, not the number of entries on that database.

**Comment by RobLoach** [comment]
One way to show this would be some benchmarks. A concern that Twin had was for low-powered devices. It would be possible to spin up a libretro-database-extras with the entire collection.

Just don't want to add so many since we're not truly optimized and battle-tested database system in RA.

**Pull request merged**
