### PR TITLE
Add NeoGeo CD BIOS

### PR DESCRIPTION
**Pull request by LodanZark**
Add NeoGeo CD BIOS for lr-neocd core
more info:
https://github.com/libretro/neocd_libretro/issues/52

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks alot! Was curious about this.

**Comment by Freeben666** [comment]
Hi,

I grabbed the SMKDAN BIOS files, but I'm still missing 3 files (neocd_f.rom, neocd_t.rom and neocd_z.rom). Can you confirm these are supposed to come from SMKDAN or should I look elsewhere?

Regards

**Comment by LodanZark** [comment]
> Hi,
> 
> I grabbed the SMKDAN BIOS files, but I'm still missing 3 files (neocd_f.rom, neocd_t.rom and neocd_z.rom). Can you confirm these are supposed to come from SMKDAN or should I look elsewhere?
> 
> Regards

No, It doesn't come from SMKDAN, I couldn't figure it out this files origins, but if you're interested to get them, I attached the IPS patches to this reply (to be applied on neocd.bin crc32 df9de490).

[IPSPatches.zip](https://github.com/libretro/libretro-database/files/5377615/IPSPatches.zip)

**Comment by Freeben666** [comment]
Thanks @LodanZark , I now have a full set ;-)

**Pull request merged**
