### PR TITLE
Add N64 cheats

### PR DESCRIPTION
**Pull request by loganmc10**
Fixes https://github.com/libretro/libretro-database/issues/388

thanks to @bparker06

### CODE REVIEW

**Comment by RobLoach** [comment]
Before we merge this, does it work through the menu? I'll be able to test tonight as well.

**Comment by loganmc10** [comment]
Do you mean applying cheats through the RetroArch menu?
image

I don't actually know any other way to do it, but yes I tested that and it seems to be working fine.

**Comment by RobLoach** [comment]
1. Loaded Super Smash Bros 64
2. Loaded the Nintendo 64 cheat file for it
3. Enabled the "Have all characters" cheat
4. Applied the Cheat Changes
4. Saw that I didn't have all characters

Do I need to restart the game to apply them?

**Comment by loganmc10** [comment]
I believe for that cheat to work you need to grab the version under "SMASH BROTHERS", and you can't be "looking" at the character selection screen when you do it. Worked for me in those circumstances.

I'm not sure why there are multiple cheat files for each game with different names, that's how it was in the upstream file.

**Comment by RobLoach** [comment]
@loganmc10 Do you know if @bparker06 has the script anymore? Might be good to hold onto it somewhere so that when mupen64 updates their cheat file, we can bring in the new changes.

**Comment by loganmc10** [comment]
@bparker06 wrote it today, so he definitely has it, I don't have a copy of it though

**Pull request merged**
