### PR TITLE
Adding pokemon prism to the database along with c_converter 

### PR DESCRIPTION
**Pull request by fennectech**
Any issues you see here
Also added c_converter so users dont need to compile it from libretro-super drasticly lowering the bar for users to contribute to the database.

### CODE REVIEW

**Comment by fennectech** [comment]
it appears c_converter is breaking the databases
Dont merge this unless you want to rebuild the database.

**Comment by RobLoach** [comment]
It looks like you've added the entire database. I'd recommend two things to make it easier for you...

1. Add the individual entries to [hacks/Nintendo - Game Boy Color.dat](https://github.com/libretro/libretro-database/blob/master/metadat/hacks/Nintendo%20-%20Game%20Boy%20Color.dat)
2. Use the EDIT button to add it directly through the web interface
3. Don't worry about adding c_converter. The buildbot manages compilation for us. libretro-super's build-database also handles compiling all the dats together.

**Comment by fennectech** [comment]
so. should i revert everything here?

**Comment by RobLoach** [comment]
Doing it through the GitHub UI should resolve it as a new branch in a new PR. Let me know if you'd like any help on getting that in :wink:

**Pull request closed without merging**
